#!/bin/bash

echo "🚀 基金估值系统 - MongoDB Atlas 配置向导"
echo ""
echo "请按照以下步骤操作："
echo ""
echo "1️⃣  访问 MongoDB Atlas"
echo "   https://www.mongodb.com/cloud/atlas"
echo ""
echo "2️⃣  注册/登录账号"
echo "   - 使用 Google/GitHub 账号快速登录"
echo "   - 或使用邮箱注册"
echo ""
echo "3️⃣  创建免费集群"
echo "   - 点击 'Build a Database'"
echo "   - 选择 'M0 Free' 套餐"
echo "   - 选择区域：推荐 'Singapore' 或 'Hong Kong'"
echo "   - 点击 'Create'"
echo ""
echo "4️⃣  创建数据库用户"
echo "   - 设置用户名和密码（记住这个密码！）"
echo "   - 点击 'Create User'"
echo ""
echo "5️⃣  配置网络访问"
echo "   - 点击 'Add IP Address'"
echo "   - 选择 'Allow Access from Anywhere' (0.0.0.0/0)"
echo "   - 点击 'Confirm'"
echo ""
echo "6️⃣  获取连接字符串"
echo "   - 点击 'Connect'"
echo "   - 选择 'Connect your application'"
echo "   - 复制连接字符串"
echo "   - 格式：mongodb+srv://username:password@cluster.mongodb.net/..."
echo ""
echo "7️⃣  配置环境变量"
echo "   - 复制 .env.example 为 .env.local"
echo "   - 填入你的 MONGODB_URI"
echo ""
echo "8️⃣  测试连接"
echo "   - 运行 npm run dev"
echo "   - 注册一个账号测试"
echo ""
echo "✅ 完成！数据现在会持久化到 MongoDB Atlas"
echo ""
echo "💡 提示："
echo "   - 免费套餐：512 MB 存储"
echo "   - 足够存储数千个用户和基金数据"
echo "   - 国内访问速度良好"
echo ""
